class Category_485 {
	class G36C_DZ {
		type = "trade_weapons";
		buy[] = {6000,"worth"};
		sell[] = {2000,"worth"};
	};
	class G36C_camo {
		type = "trade_weapons";
		buy[] = {7000,"worth"};
		sell[] = {3000,"worth"};
	};
	class G36A_Camo_DZ {
		type = "trade_weapons";
		buy[] = {7000,"worth"};
		sell[] = {3000,"worth"};
	};
	class G36K_Camo_DZ {
		type = "trade_weapons";
		buy[] = {7000,"worth"};
		sell[] = {3000,"worth"};
	};
	class M16A2_DZ {
		type = "trade_weapons";
		buy[] = {5000,"worth"};
		sell[] = {1000,"worth"};
	};
	class M16A4_DZ {
		type = "trade_weapons";
		buy[] = {6000,"worth"};
		sell[] = {2000,"worth"};
	};
	class M4A1_DZ {
		type = "trade_weapons";
		buy[] = {5000,"worth"};
		sell[] = {2000,"worth"};
	};
	class M4A1_HWS_GL_camo {
		type = "trade_weapons";
		buy[] = {8000,"worth"};
		sell[] = {4000,"worth"};
	};
	class M4A1_HWS_GL_SD_Camo {
		type = "trade_weapons";
		buy[] = {20000,"worth"};
		sell[] = {10000,"worth"};
	};
	class M4A3_CCO_EP1 {
		type = "trade_weapons";
		buy[] = {10000,"worth"};
		sell[] = {5000,"worth"};
	};
	class SCAR_L_CQC {
		type = "trade_weapons";
		buy[] = {10000,"worth"};
		sell[] = {3000,"worth"};
	};
	class SCAR_L_CQC_CCO_SD {
		type = "trade_weapons";
		buy[] = {20000,"worth"};
		sell[] = {8000,"worth"};
	};
	class SCAR_L_CQC_Holo {
		type = "trade_weapons";
		buy[] = {12000,"worth"};
		sell[] = {4000,"worth"};
	};
	class SCAR_L_CQC_EGLM_Holo {
		type = "trade_weapons";
		buy[] = {12000,"worth"};
		sell[] = {5000,"worth"};
	};
	class SCAR_L_STD_EGLM_RCO {
		type = "trade_weapons";
		buy[] = {20000,"worth"};
		sell[] = {7000,"worth"};
	};
	class SCAR_L_STD_HOLO {
		type = "trade_weapons";
		buy[] = {12000,"worth"};
		sell[] = {4000,"worth"};
	};
	class SCAR_L_STD_Mk4CQT {
		type = "trade_weapons";
		buy[] = {12000,"worth"};
		sell[] = {4000,"worth"};
	};
	class L85_Holo_DZ {
		type = "trade_weapons";
		buy[] = {10000,"worth"};
		sell[] = {2000,"worth"};
	};
	class BAF_L85A2_RIS_SUSAT {
		type = "trade_weapons";
		buy[] = {10000,"worth"};
		sell[] = {3000,"worth"};
	};
	class BAF_L85A2_RIS_ACOG {
		type = "trade_weapons";
		buy[] = {10000,"worth"};
		sell[] = {5000,"worth"};
	};
	class SA58_DZ {
		type = "trade_weapons";
		buy[] = {5000,"worth"};
		sell[] = {1000,"worth"};
	};
	class Sa58V_CCO_EP1 {
		type = "trade_weapons";
		buy[] = {5500,"worth"};
		sell[] = {2000,"worth"};
	};
	class Sa58V_RCO_EP1 {
		type = "trade_weapons";
		buy[] = {8000,"worth"};
		sell[] = {4000,"worth"};
	};
	class AKS74U_DZ {
		type = "trade_weapons";
		buy[] = {10000,"worth"};
		sell[] = {1000,"worth"};
	};
	class AKM_DZ {
		type = "trade_weapons";
		buy[] = {10000,"worth"};
		sell[] = {3000,"worth"};
	};
	class AK74_DZ {
		type = "trade_weapons";
		buy[] = {20000,"worth"};
		sell[] = {1000,"worth"};
	};
	class FNFAL_DZ {
		type = "trade_weapons";
		buy[] = {25000,"worth"};
		sell[] = {4000,"worth"};
	};
	class FN_FAL_ANPVS4_DZE {
		type = "trade_weapons";
		buy[] = {28000,"worth"};
		sell[] = {10000,"worth"};
	};
class FHQ_ACR_WDL_IRN {type = "trade_weapons";buy[] = {10000,"Coins"};sell[] = {5000,"Coins"};};
class FHQ_ACR_WDL_IRN_F {type = "trade_weapons";buy[] = {10000,"Coins"};sell[] = {5000,"Coins"};};
class FHQ_ACR_WDL_IRN_GL {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_WDL_IRN_GL_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_WDL_IRN_GL_SD {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_IRN_GL_SD_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_IRN_SD {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_IRN_SD_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_RCO {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_RCO_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_RCO_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_RCO_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_RCO_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_WDL_RCO_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_WDL_RCO_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_WDL_RCO_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_BLK_CCO {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_CCO_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_CCO_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_CCO_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_CCO_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_BLK_CCO_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_BLK_CCO_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_BLK_CCO_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_BLK_G33 {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_G33_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_G33_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_G33_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_G33_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_BLK_G33_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_BLK_G33_SD {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_G33_SD_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_HAMR {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_HAMR_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_HAMR_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_HAMR_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_HAMR_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_BLK_HAMR_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_BLK_HAMR_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_BLK_HAMR_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_BLK_HWS {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_HWS_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_HWS_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_HWS_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_HWS_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_BLK_HWS_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_BLK_HWS_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_BLK_HWS_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_BLK_IRN {type = "trade_weapons";buy[] = {10000,"Coins"};sell[] = {5000,"Coins"};};
class FHQ_ACR_BLK_IRN_F {type = "trade_weapons";buy[] = {10000,"Coins"};sell[] = {5000,"Coins"};};
class FHQ_ACR_BLK_IRN_GL {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_BLK_IRN_GL_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_BLK_IRN_GL_SD {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_IRN_GL_SD_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_IRN_SD {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_IRN_SD_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_RCO {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_RCO_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_BLK_RCO_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_RCO_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_BLK_RCO_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_BLK_RCO_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_BLK_RCO_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_BLK_RCO_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_CCO {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_CCO_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_CCO_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_CCO_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_CCO_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_SNW_CCO_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_SNW_CCO_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_CCO_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_G33 {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_G33_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_G33_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_G33_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_G33_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_SNW_G33_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_SNW_G33_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_G33_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_HAMR {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_HAMR_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_HAMR_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_HAMR_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_HAMR_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_SNW_HAMR_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_SNW_HAMR_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_HAMR_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_HWS {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_HWS_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_HWS_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_HWS_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_HWS_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_SNW_HWS_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_SNW_HWS_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_HWS_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_IRN {type = "trade_weapons";buy[] = {10000,"Coins"};sell[] = {5000,"Coins"};};
class FHQ_ACR_SNW_IRN_F {type = "trade_weapons";buy[] = {10000,"Coins"};sell[] = {5000,"Coins"};};
class FHQ_ACR_SNW_IRN_GL {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_IRN_GL_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_IRN_GL_SD {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_IRN_GL_SD_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_IRN_SD {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_IRN_SD_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_RCO {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_RCO_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_SNW_RCO_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_RCO_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_SNW_RCO_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_SNW_RCO_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_SNW_RCO_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_SNW_RCO_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_TAN_CCO {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_CCO_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_CCO_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_CCO_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_CCO_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_TAN_CCO_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_TAN_CCO_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_TAN_CCO_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_TAN_G33 {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_G33_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_G33_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_G33_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_G33_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_TAN_G33_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_TAN_G33_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_TAN_G33_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_TAN_HAMR {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_HAMR_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_HAMR_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_HAMR_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_HAMR_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_TAN_HAMR_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_TAN_HAMR_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_TAN_HAMR_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_TAN_HWS {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_HWS_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_HWS_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_HWS_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_HWS_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_TAN_HWS_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_TAN_HWS_SD {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_HWS_SD_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_IRN {type = "trade_weapons";buy[] = {10000,"Coins"};sell[] = {5000,"Coins"};};
class FHQ_ACR_TAN_IRN_F {type = "trade_weapons";buy[] = {10000,"Coins"};sell[] = {5000,"Coins"};};
class FHQ_ACR_TAN_IRN_GL {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_TAN_IRN_GL_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_TAN_IRN_GL_SD {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_IRN_GL_SD_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_IRN_SD {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_IRN_SD_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_RCO {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_RCO_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_TAN_RCO_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_RCO_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_TAN_RCO_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_TAN_RCO_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_TAN_RCO_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_TAN_RCO_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_WDL_CCO {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_CCO_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_CCO_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_CCO_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_CCO_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_WDL_CCO_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_WDL_CCO_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_WDL_CCO_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_WDL_G33 {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_G33_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_G33_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_G33_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_G33_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_WDL_G33_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_WDL_G33_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_WDL_G33_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_WDL_HAMR {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_HAMR_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_HAMR_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_HAMR_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_HAMR_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_WDL_HAMR_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_WDL_HAMR_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_WDL_HAMR_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_WDL_HWS {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_HWS_F {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class FHQ_ACR_WDL_HWS_GL {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_HWS_GL_F {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class FHQ_ACR_WDL_HWS_GL_SD {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_WDL_HWS_GL_SD_F {type = "trade_weapons";buy[] = {10800,"Coins"};sell[] = {5400,"Coins"};};
class FHQ_ACR_WDL_HWS_SD {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class FHQ_ACR_WDL_HWS_SD_F {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class RH_acr {type = "trade_weapons";buy[] = {10000,"Coins"};sell[] = {5000,"Coins"};};
class RH_acracog {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class RH_acraim {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class RH_acrb {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class RH_acrbacog {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class RH_acrbaim {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class RH_acrbeotech {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class RH_acrbgl {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class RH_acrbglacog {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class RH_acrbglaim {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class RH_acrbgleotech {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class RH_acreotech {type = "trade_weapons";buy[] = {10200,"Coins"};sell[] = {5100,"Coins"};};
class RH_acrgl {type = "trade_weapons";buy[] = {10400,"Coins"};sell[] = {5200,"Coins"};};
class RH_acrglacog {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class RH_acrglaim {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class RH_acrgleotech {type = "trade_weapons";buy[] = {10600,"Coins"};sell[] = {5300,"Coins"};};
class RH_ctar21 {type = "trade_weapons";buy[] = {4000,"Coins"};sell[] = {2000,"Coins"};};
class RH_ctar21glacog {type = "trade_weapons";buy[] = {4600,"Coins"};sell[] = {2300,"Coins"};};
class RH_ctar21m {type = "trade_weapons";buy[] = {4200,"Coins"};sell[] = {2200,"Coins"};};
class RH_ctar21mgl {type = "trade_weapons";buy[] = {4600,"Coins"};sell[] = {2300,"Coins"};};
};